title = 'Based Cooking'
baseURL = 'https://based.cooking/'
locale = 'en-us'
theme = 'lugo'

[params]
  favicon = "/favicon.svg"
  stylesheet = "/style.css"
  indexarticles = 50
  taglist = true
  datesinlist = false
  authorsinlist = false
  nextprev = true
  showrss = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
