baseURL = 'https://publicdomainrecipes.com'
languageCode = 'en-us'
title = 'Public Domain Recipes'
theme = 'lugo'

[params]
  favicon = "/favicon.svg"
  stylesheet = "/style.css"
  indexarticles = 50
  taglist = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
theme = 'lugo'
