#!/bin/sh

test -n "$COOKPATH" || COOKPATH="/usr/share/cooking"

die() {
    printf "$1\n" 1>&2
    exit 1
}

get_recipes() {
    find "$COOKPATH" -name '*.1'
}

list_recipes() {
    for f in $(get_recipes) ; do
        base="${f##*/}"
        printf "${base%.1}\n"
    done | sort
}

search_recipe() {
    grep -Rli "$1" "$COOKPATH" | sed -e 's;^.*/\([^/]*\).1;\1;g'
}

open_recipe() {
    path="$(find "$COOKPATH" -name "$1.1")"
    test -f "$path" || die "No such recipe: $1"
    man "$path"
}

help() {
    printf "$0 [<recipe>|-s <query>]\n"
    printf "    If no argument given, will list all recipes found in \$COOKPATH and sub folders\n"
    printf "    <recipe>: open recipe with given name\n"
    printf "    -s <query>: greps for <query> in all installed recipes, case insensitive\n"
}

if [ "$#" -eq 0 ] ; then
    list_recipes
else
    case "$1" in
        -s)
            shift
            search_recipe "$@"
            ;;
        -h)
            help
            ;;
        *)
            open_recipe "$1"
            ;;
    esac
fi
