#!/bin/sh

# If you're Luke, add an arg to update the website too.

#rm dest -rf
#mkdir -p dest
ssg5 src dest "Based Cooking (https://based.cooking)" "https://based.cooking"

[ -n "$1" ] &&
	rsync -auvrlP --delete-after ~/.local/src/food/ root@based.cooking:/var/www/cooking
